<?php

namespace Modules\Accounting\Support;

/**
 * Türkiye Tekdüzen Hesap Planı (TDHP) — 3-basamaklı yasal ana hesaplar.
 * Her tenant provision'ında `is_system=true` olarak seed edilir; kod ve type
 * yasal sabittir, kullanıcı yalnız altına 4+ basamaklı alt hesap açabilir.
 *
 * Type sınıflandırması:
 *   1xx-2xx → asset
 *   3xx-4xx → liability
 *   5xx     → equity
 *   6xx     → income (60,64,67,69) | expense (61,62,63,65,66,68)
 *   7xx     → expense
 */
final class TekduzenHesapPlani
{
    /**
     * @return array<int, array{code: string, name: string, type: string}>
     */
    public static function accounts(): array
    {
        return [
            // 1. DÖNEN VARLIKLAR
            ['code' => '100', 'name' => 'Kasa', 'type' => 'asset'],
            ['code' => '101', 'name' => 'Alınan Çekler', 'type' => 'asset'],
            ['code' => '102', 'name' => 'Bankalar', 'type' => 'asset'],
            ['code' => '103', 'name' => 'Verilen Çekler ve Ödeme Emirleri (-)', 'type' => 'asset'],
            ['code' => '108', 'name' => 'Diğer Hazır Değerler', 'type' => 'asset'],
            ['code' => '110', 'name' => 'Hisse Senetleri', 'type' => 'asset'],
            ['code' => '111', 'name' => 'Özel Kesim Tahvil, Senet ve Bonoları', 'type' => 'asset'],
            ['code' => '112', 'name' => 'Kamu Kesimi Tahvil, Senet ve Bonoları', 'type' => 'asset'],
            ['code' => '118', 'name' => 'Diğer Menkul Kıymetler', 'type' => 'asset'],
            ['code' => '119', 'name' => 'Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)', 'type' => 'asset'],
            ['code' => '120', 'name' => 'Alıcılar', 'type' => 'asset'],
            ['code' => '121', 'name' => 'Alacak Senetleri', 'type' => 'asset'],
            ['code' => '122', 'name' => 'Alacak Senetleri Reeskontu (-)', 'type' => 'asset'],
            ['code' => '124', 'name' => 'Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)', 'type' => 'asset'],
            ['code' => '126', 'name' => 'Verilen Depozito ve Teminatlar', 'type' => 'asset'],
            ['code' => '127', 'name' => 'Diğer Ticari Alacaklar', 'type' => 'asset'],
            ['code' => '128', 'name' => 'Şüpheli Ticari Alacaklar', 'type' => 'asset'],
            ['code' => '129', 'name' => 'Şüpheli Ticari Alacaklar Karşılığı (-)', 'type' => 'asset'],
            ['code' => '131', 'name' => 'Ortaklardan Alacaklar', 'type' => 'asset'],
            ['code' => '132', 'name' => 'İştiraklerden Alacaklar', 'type' => 'asset'],
            ['code' => '133', 'name' => 'Bağlı Ortaklıklardan Alacaklar', 'type' => 'asset'],
            ['code' => '135', 'name' => 'Personelden Alacaklar', 'type' => 'asset'],
            ['code' => '136', 'name' => 'Diğer Çeşitli Alacaklar', 'type' => 'asset'],
            ['code' => '137', 'name' => 'Diğer Alacak Senetleri Reeskontu (-)', 'type' => 'asset'],
            ['code' => '138', 'name' => 'Şüpheli Diğer Alacaklar', 'type' => 'asset'],
            ['code' => '139', 'name' => 'Şüpheli Diğer Alacaklar Karşılığı (-)', 'type' => 'asset'],
            ['code' => '150', 'name' => 'İlk Madde ve Malzeme', 'type' => 'asset'],
            ['code' => '151', 'name' => 'Yarı Mamuller - Üretim', 'type' => 'asset'],
            ['code' => '152', 'name' => 'Mamuller', 'type' => 'asset'],
            ['code' => '153', 'name' => 'Ticari Mallar', 'type' => 'asset'],
            ['code' => '157', 'name' => 'Diğer Stoklar', 'type' => 'asset'],
            ['code' => '158', 'name' => 'Stok Değer Düşüklüğü Karşılığı (-)', 'type' => 'asset'],
            ['code' => '159', 'name' => 'Verilen Sipariş Avansları', 'type' => 'asset'],
            ['code' => '170', 'name' => 'Yıllara Yaygın İnşaat ve Onarım Maliyetleri', 'type' => 'asset'],
            ['code' => '178', 'name' => 'Yıllara Yaygın İnşaat Enflasyon Düzeltme Hesabı', 'type' => 'asset'],
            ['code' => '179', 'name' => 'Taşeronlara Verilen Avanslar', 'type' => 'asset'],
            ['code' => '180', 'name' => 'Gelecek Aylara Ait Giderler', 'type' => 'asset'],
            ['code' => '181', 'name' => 'Gelir Tahakkukları', 'type' => 'asset'],
            ['code' => '190', 'name' => 'Devreden KDV', 'type' => 'asset'],
            ['code' => '191', 'name' => 'İndirilecek KDV', 'type' => 'asset'],
            ['code' => '192', 'name' => 'Diğer KDV', 'type' => 'asset'],
            ['code' => '193', 'name' => 'Peşin Ödenen Vergiler ve Fonlar', 'type' => 'asset'],
            ['code' => '195', 'name' => 'İş Avansları', 'type' => 'asset'],
            ['code' => '196', 'name' => 'Personel Avansları', 'type' => 'asset'],
            ['code' => '197', 'name' => 'Sayım ve Tesellüm Noksanları', 'type' => 'asset'],
            ['code' => '198', 'name' => 'Diğer Çeşitli Dönen Varlıklar', 'type' => 'asset'],
            ['code' => '199', 'name' => 'Diğer Dönen Varlıklar Karşılığı (-)', 'type' => 'asset'],

            // 2. DURAN VARLIKLAR
            ['code' => '220', 'name' => 'Alıcılar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '221', 'name' => 'Alacak Senetleri (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '222', 'name' => 'Alacak Senetleri Reeskontu (Uzun Vadeli) (-)', 'type' => 'asset'],
            ['code' => '224', 'name' => 'Kazanılmamış Finansal Kiralama Faiz Gelirleri (Uzun Vadeli) (-)', 'type' => 'asset'],
            ['code' => '226', 'name' => 'Verilen Depozito ve Teminatlar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '229', 'name' => 'Şüpheli Alacaklar Karşılığı (Uzun Vadeli) (-)', 'type' => 'asset'],
            ['code' => '231', 'name' => 'Ortaklardan Alacaklar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '232', 'name' => 'İştiraklerden Alacaklar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '233', 'name' => 'Bağlı Ortaklıklardan Alacaklar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '235', 'name' => 'Personelden Alacaklar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '236', 'name' => 'Diğer Çeşitli Alacaklar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '237', 'name' => 'Diğer Alacak Senetleri Reeskontu (Uzun Vadeli) (-)', 'type' => 'asset'],
            ['code' => '239', 'name' => 'Şüpheli Diğer Alacaklar Karşılığı (Uzun Vadeli) (-)', 'type' => 'asset'],
            ['code' => '240', 'name' => 'Bağlı Menkul Kıymetler', 'type' => 'asset'],
            ['code' => '241', 'name' => 'Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)', 'type' => 'asset'],
            ['code' => '242', 'name' => 'İştirakler', 'type' => 'asset'],
            ['code' => '243', 'name' => 'İştiraklere Sermaye Taahhütleri (-)', 'type' => 'asset'],
            ['code' => '244', 'name' => 'İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)', 'type' => 'asset'],
            ['code' => '245', 'name' => 'Bağlı Ortaklıklar', 'type' => 'asset'],
            ['code' => '246', 'name' => 'Bağlı Ortaklıklar Sermaye Taahhütleri (-)', 'type' => 'asset'],
            ['code' => '247', 'name' => 'Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)', 'type' => 'asset'],
            ['code' => '248', 'name' => 'Diğer Mali Duran Varlıklar', 'type' => 'asset'],
            ['code' => '249', 'name' => 'Diğer Mali Duran Varlıklar Karşılığı (-)', 'type' => 'asset'],
            ['code' => '250', 'name' => 'Arazi ve Arsalar', 'type' => 'asset'],
            ['code' => '251', 'name' => 'Yeraltı ve Yerüstü Düzenleri', 'type' => 'asset'],
            ['code' => '252', 'name' => 'Binalar', 'type' => 'asset'],
            ['code' => '253', 'name' => 'Tesis, Makine ve Cihazlar', 'type' => 'asset'],
            ['code' => '254', 'name' => 'Taşıtlar', 'type' => 'asset'],
            ['code' => '255', 'name' => 'Demirbaşlar', 'type' => 'asset'],
            ['code' => '256', 'name' => 'Diğer Maddi Duran Varlıklar', 'type' => 'asset'],
            ['code' => '257', 'name' => 'Birikmiş Amortismanlar (-)', 'type' => 'asset'],
            ['code' => '258', 'name' => 'Yapılmakta Olan Yatırımlar', 'type' => 'asset'],
            ['code' => '259', 'name' => 'Verilen Avanslar', 'type' => 'asset'],
            ['code' => '260', 'name' => 'Haklar', 'type' => 'asset'],
            ['code' => '261', 'name' => 'Şerefiye', 'type' => 'asset'],
            ['code' => '262', 'name' => 'Kuruluş ve Örgütlenme Giderleri', 'type' => 'asset'],
            ['code' => '263', 'name' => 'Araştırma ve Geliştirme Giderleri', 'type' => 'asset'],
            ['code' => '264', 'name' => 'Özel Maliyetler', 'type' => 'asset'],
            ['code' => '267', 'name' => 'Diğer Maddi Olmayan Duran Varlıklar', 'type' => 'asset'],
            ['code' => '268', 'name' => 'Birikmiş Amortismanlar (Maddi Olmayan) (-)', 'type' => 'asset'],
            ['code' => '269', 'name' => 'Verilen Avanslar (Maddi Olmayan)', 'type' => 'asset'],
            ['code' => '271', 'name' => 'Arama Giderleri', 'type' => 'asset'],
            ['code' => '272', 'name' => 'Hazırlık ve Geliştirme Giderleri', 'type' => 'asset'],
            ['code' => '277', 'name' => 'Diğer Özel Tükenmeye Tabi Varlıklar', 'type' => 'asset'],
            ['code' => '278', 'name' => 'Birikmiş Tükenme Payları (-)', 'type' => 'asset'],
            ['code' => '279', 'name' => 'Verilen Avanslar (Özel Tükenmeye Tabi)', 'type' => 'asset'],
            ['code' => '280', 'name' => 'Gelecek Yıllara Ait Giderler', 'type' => 'asset'],
            ['code' => '281', 'name' => 'Gelir Tahakkukları (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '291', 'name' => 'Gelecek Yıllarda İndirilecek KDV', 'type' => 'asset'],
            ['code' => '292', 'name' => 'Diğer KDV (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '293', 'name' => 'Gelecek Yıllar İhtiyacı Stoklar', 'type' => 'asset'],
            ['code' => '294', 'name' => 'Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar', 'type' => 'asset'],
            ['code' => '295', 'name' => 'Peşin Ödenen Vergiler ve Fonlar (Uzun Vadeli)', 'type' => 'asset'],
            ['code' => '297', 'name' => 'Diğer Çeşitli Duran Varlıklar', 'type' => 'asset'],
            ['code' => '298', 'name' => 'Stok Değer Düşüklüğü Karşılığı (Uzun Vadeli) (-)', 'type' => 'asset'],
            ['code' => '299', 'name' => 'Birikmiş Amortismanlar (Diğer Duran) (-)', 'type' => 'asset'],

            // 3. KISA VADELİ YABANCI KAYNAKLAR
            ['code' => '300', 'name' => 'Banka Kredileri', 'type' => 'liability'],
            ['code' => '301', 'name' => 'Finansal Kiralama İşlemlerinden Borçlar', 'type' => 'liability'],
            ['code' => '302', 'name' => 'Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)', 'type' => 'liability'],
            ['code' => '303', 'name' => 'Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri', 'type' => 'liability'],
            ['code' => '304', 'name' => 'Tahvil Anapara Borç, Taksit ve Faizleri', 'type' => 'liability'],
            ['code' => '305', 'name' => 'Çıkarılmış Bonolar ve Senetler', 'type' => 'liability'],
            ['code' => '306', 'name' => 'Çıkarılmış Diğer Menkul Kıymetler', 'type' => 'liability'],
            ['code' => '308', 'name' => 'Menkul Kıymetler İhraç Farkları (-)', 'type' => 'liability'],
            ['code' => '309', 'name' => 'Diğer Mali Borçlar', 'type' => 'liability'],
            ['code' => '320', 'name' => 'Satıcılar', 'type' => 'liability'],
            ['code' => '321', 'name' => 'Borç Senetleri', 'type' => 'liability'],
            ['code' => '322', 'name' => 'Borç Senetleri Reeskontu (-)', 'type' => 'liability'],
            ['code' => '326', 'name' => 'Alınan Depozito ve Teminatlar', 'type' => 'liability'],
            ['code' => '329', 'name' => 'Diğer Ticari Borçlar', 'type' => 'liability'],
            ['code' => '331', 'name' => 'Ortaklara Borçlar', 'type' => 'liability'],
            ['code' => '332', 'name' => 'İştiraklere Borçlar', 'type' => 'liability'],
            ['code' => '333', 'name' => 'Bağlı Ortaklıklara Borçlar', 'type' => 'liability'],
            ['code' => '335', 'name' => 'Personele Borçlar', 'type' => 'liability'],
            ['code' => '336', 'name' => 'Diğer Çeşitli Borçlar', 'type' => 'liability'],
            ['code' => '337', 'name' => 'Diğer Borç Senetleri Reeskontu (-)', 'type' => 'liability'],
            ['code' => '340', 'name' => 'Alınan Sipariş Avansları', 'type' => 'liability'],
            ['code' => '349', 'name' => 'Alınan Diğer Avanslar', 'type' => 'liability'],
            ['code' => '350', 'name' => 'Yıllara Yaygın İnşaat ve Onarım Hakedişleri', 'type' => 'liability'],
            ['code' => '358', 'name' => 'Yıllara Yaygın İnşaat Enflasyon Düzeltme Hesabı', 'type' => 'liability'],
            ['code' => '360', 'name' => 'Ödenecek Vergi ve Fonlar', 'type' => 'liability'],
            ['code' => '361', 'name' => 'Ödenecek Sosyal Güvenlik Kesintileri', 'type' => 'liability'],
            ['code' => '368', 'name' => 'Vadesi Geçmiş, Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler', 'type' => 'liability'],
            ['code' => '369', 'name' => 'Ödenecek Diğer Yükümlülükler', 'type' => 'liability'],
            ['code' => '370', 'name' => 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları', 'type' => 'liability'],
            ['code' => '371', 'name' => 'Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)', 'type' => 'liability'],
            ['code' => '372', 'name' => 'Kıdem Tazminatı Karşılığı', 'type' => 'liability'],
            ['code' => '373', 'name' => 'Maliyet Giderleri Karşılığı', 'type' => 'liability'],
            ['code' => '379', 'name' => 'Diğer Borç ve Gider Karşılıkları', 'type' => 'liability'],
            ['code' => '380', 'name' => 'Gelecek Aylara Ait Gelirler', 'type' => 'liability'],
            ['code' => '381', 'name' => 'Gider Tahakkukları', 'type' => 'liability'],
            ['code' => '391', 'name' => 'Hesaplanan KDV', 'type' => 'liability'],
            ['code' => '392', 'name' => 'Diğer KDV (KV Yabancı Kaynaklar)', 'type' => 'liability'],
            ['code' => '393', 'name' => 'Merkez ve Şubeler Cari Hesabı', 'type' => 'liability'],
            ['code' => '397', 'name' => 'Sayım ve Tesellüm Fazlaları', 'type' => 'liability'],
            ['code' => '399', 'name' => 'Diğer Çeşitli Yabancı Kaynaklar', 'type' => 'liability'],

            // 4. UZUN VADELİ YABANCI KAYNAKLAR
            ['code' => '400', 'name' => 'Banka Kredileri (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '401', 'name' => 'Finansal Kiralama İşlemlerinden Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '402', 'name' => 'Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (Uzun Vadeli) (-)', 'type' => 'liability'],
            ['code' => '405', 'name' => 'Çıkarılmış Tahviller', 'type' => 'liability'],
            ['code' => '407', 'name' => 'Çıkarılmış Diğer Menkul Kıymetler (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '408', 'name' => 'Menkul Kıymetler İhraç Farkı (Uzun Vadeli) (-)', 'type' => 'liability'],
            ['code' => '409', 'name' => 'Diğer Mali Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '420', 'name' => 'Satıcılar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '421', 'name' => 'Borç Senetleri (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '422', 'name' => 'Borç Senetleri Reeskontu (Uzun Vadeli) (-)', 'type' => 'liability'],
            ['code' => '426', 'name' => 'Alınan Depozito ve Teminatlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '429', 'name' => 'Diğer Ticari Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '431', 'name' => 'Ortaklara Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '432', 'name' => 'İştiraklere Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '433', 'name' => 'Bağlı Ortaklıklara Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '436', 'name' => 'Diğer Çeşitli Borçlar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '437', 'name' => 'Diğer Borç Senetleri Reeskontu (Uzun Vadeli) (-)', 'type' => 'liability'],
            ['code' => '438', 'name' => 'Kamuya Olan Ertelenmiş veya Taksitlendirilmiş Borçlar', 'type' => 'liability'],
            ['code' => '440', 'name' => 'Alınan Sipariş Avansları (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '449', 'name' => 'Alınan Diğer Avanslar (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '472', 'name' => 'Kıdem Tazminatı Karşılığı (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '479', 'name' => 'Diğer Borç ve Gider Karşılıkları (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '480', 'name' => 'Gelecek Yıllara Ait Gelirler', 'type' => 'liability'],
            ['code' => '481', 'name' => 'Gider Tahakkukları (Uzun Vadeli)', 'type' => 'liability'],
            ['code' => '492', 'name' => 'Gelecek Yıllara Ertelenen veya Terkin Edilecek KDV', 'type' => 'liability'],
            ['code' => '493', 'name' => 'Tesise Katılma Payları', 'type' => 'liability'],
            ['code' => '499', 'name' => 'Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar', 'type' => 'liability'],

            // 5. ÖZ KAYNAKLAR
            ['code' => '500', 'name' => 'Sermaye', 'type' => 'equity'],
            ['code' => '501', 'name' => 'Ödenmemiş Sermaye (-)', 'type' => 'equity'],
            ['code' => '502', 'name' => 'Sermaye Düzeltmesi Olumlu Farkları', 'type' => 'equity'],
            ['code' => '503', 'name' => 'Sermaye Düzeltmesi Olumsuz Farkları (-)', 'type' => 'equity'],
            ['code' => '520', 'name' => 'Hisse Senedi İhraç Primleri', 'type' => 'equity'],
            ['code' => '521', 'name' => 'Hisse Senedi İptal Karları', 'type' => 'equity'],
            ['code' => '522', 'name' => 'MDV Yeniden Değerleme Artışları', 'type' => 'equity'],
            ['code' => '523', 'name' => 'İştirakler Yeniden Değerleme Artışları', 'type' => 'equity'],
            ['code' => '524', 'name' => 'Maliyet Artışları Fonu', 'type' => 'equity'],
            ['code' => '529', 'name' => 'Diğer Sermaye Yedekleri', 'type' => 'equity'],
            ['code' => '540', 'name' => 'Yasal Yedekler', 'type' => 'equity'],
            ['code' => '541', 'name' => 'Statü Yedekleri', 'type' => 'equity'],
            ['code' => '542', 'name' => 'Olağanüstü Yedekler', 'type' => 'equity'],
            ['code' => '548', 'name' => 'Diğer Kar Yedekleri', 'type' => 'equity'],
            ['code' => '549', 'name' => 'Özel Fonlar', 'type' => 'equity'],
            ['code' => '570', 'name' => 'Geçmiş Yıllar Karları', 'type' => 'equity'],
            ['code' => '580', 'name' => 'Geçmiş Yıllar Zararları (-)', 'type' => 'equity'],
            ['code' => '590', 'name' => 'Dönem Net Karı', 'type' => 'equity'],
            ['code' => '591', 'name' => 'Dönem Net Zararı (-)', 'type' => 'equity'],

            // 6. GELİR TABLOSU HESAPLARI
            ['code' => '600', 'name' => 'Yurtiçi Satışlar', 'type' => 'income'],
            ['code' => '601', 'name' => 'Yurtdışı Satışlar', 'type' => 'income'],
            ['code' => '602', 'name' => 'Diğer Gelirler', 'type' => 'income'],
            ['code' => '610', 'name' => 'Satıştan İadeler (-)', 'type' => 'expense'],
            ['code' => '611', 'name' => 'Satış İskontoları (-)', 'type' => 'expense'],
            ['code' => '612', 'name' => 'Diğer İndirimler (-)', 'type' => 'expense'],
            ['code' => '620', 'name' => 'Satılan Mamuller Maliyeti (-)', 'type' => 'expense'],
            ['code' => '621', 'name' => 'Satılan Ticari Mallar Maliyeti (-)', 'type' => 'expense'],
            ['code' => '622', 'name' => 'Satılan Hizmet Maliyeti (-)', 'type' => 'expense'],
            ['code' => '623', 'name' => 'Diğer Satışların Maliyeti (-)', 'type' => 'expense'],
            ['code' => '630', 'name' => 'Araştırma ve Geliştirme Giderleri (-)', 'type' => 'expense'],
            ['code' => '631', 'name' => 'Pazarlama, Satış ve Dağıtım Giderleri (-)', 'type' => 'expense'],
            ['code' => '632', 'name' => 'Genel Yönetim Giderleri (-)', 'type' => 'expense'],
            ['code' => '640', 'name' => 'İştiraklerden Temettü Gelirleri', 'type' => 'income'],
            ['code' => '641', 'name' => 'Bağlı Ortaklıklardan Temettü Gelirleri', 'type' => 'income'],
            ['code' => '642', 'name' => 'Faiz Gelirleri', 'type' => 'income'],
            ['code' => '643', 'name' => 'Komisyon Gelirleri', 'type' => 'income'],
            ['code' => '644', 'name' => 'Konusu Kalmayan Karşılıklar', 'type' => 'income'],
            ['code' => '645', 'name' => 'Menkul Kıymet Satış Karları', 'type' => 'income'],
            ['code' => '646', 'name' => 'Kambiyo Karları', 'type' => 'income'],
            ['code' => '647', 'name' => 'Reeskont Faiz Gelirleri', 'type' => 'income'],
            ['code' => '648', 'name' => 'Enflasyon Düzeltmesi Karları', 'type' => 'income'],
            ['code' => '649', 'name' => 'Diğer Olağan Gelir ve Karlar', 'type' => 'income'],
            ['code' => '653', 'name' => 'Komisyon Giderleri (-)', 'type' => 'expense'],
            ['code' => '654', 'name' => 'Karşılık Giderleri (-)', 'type' => 'expense'],
            ['code' => '655', 'name' => 'Menkul Kıymet Satış Zararları (-)', 'type' => 'expense'],
            ['code' => '656', 'name' => 'Kambiyo Zararları (-)', 'type' => 'expense'],
            ['code' => '657', 'name' => 'Reeskont Faiz Giderleri (-)', 'type' => 'expense'],
            ['code' => '658', 'name' => 'Enflasyon Düzeltmesi Zararları (-)', 'type' => 'expense'],
            ['code' => '659', 'name' => 'Diğer Olağan Gider ve Zararlar (-)', 'type' => 'expense'],
            ['code' => '660', 'name' => 'Kısa Vadeli Borçlanma Giderleri (-)', 'type' => 'expense'],
            ['code' => '661', 'name' => 'Uzun Vadeli Borçlanma Giderleri (-)', 'type' => 'expense'],
            ['code' => '671', 'name' => 'Önceki Dönem Gelir ve Karları', 'type' => 'income'],
            ['code' => '679', 'name' => 'Diğer Olağandışı Gelir ve Karlar', 'type' => 'income'],
            ['code' => '680', 'name' => 'Çalışmayan Kısım Gider ve Zararları (-)', 'type' => 'expense'],
            ['code' => '681', 'name' => 'Önceki Dönem Gider ve Zararları (-)', 'type' => 'expense'],
            ['code' => '689', 'name' => 'Diğer Olağandışı Gider ve Zararlar (-)', 'type' => 'expense'],
            ['code' => '690', 'name' => 'Dönem Karı veya Zararı', 'type' => 'equity'],
            ['code' => '691', 'name' => 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)', 'type' => 'equity'],
            ['code' => '692', 'name' => 'Dönem Net Karı veya Zararı', 'type' => 'equity'],

            // 7. MALİYET HESAPLARI (7/A)
            ['code' => '700', 'name' => 'Maliyet Muhasebesi Bağlantı Hesapları', 'type' => 'expense'],
            ['code' => '701', 'name' => 'Maliyet Muhasebesi Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '710', 'name' => 'Direkt İlk Madde ve Malzeme Giderleri', 'type' => 'expense'],
            ['code' => '711', 'name' => 'Direkt İlk Madde ve Malzeme Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '712', 'name' => 'Direkt İlk Madde ve Malzeme Fiyat Farkı', 'type' => 'expense'],
            ['code' => '713', 'name' => 'Direkt İlk Madde ve Malzeme Miktar Farkı', 'type' => 'expense'],
            ['code' => '720', 'name' => 'Direkt İşçilik Giderleri', 'type' => 'expense'],
            ['code' => '721', 'name' => 'Direkt İşçilik Giderleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '722', 'name' => 'Direkt İşçilik Ücret Farkları', 'type' => 'expense'],
            ['code' => '723', 'name' => 'Direkt İşçilik Süre (Zaman) Farkları', 'type' => 'expense'],
            ['code' => '730', 'name' => 'Genel Üretim Giderleri', 'type' => 'expense'],
            ['code' => '731', 'name' => 'Genel Üretim Giderleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '732', 'name' => 'Genel Üretim Giderleri Bütçe Farkları', 'type' => 'expense'],
            ['code' => '733', 'name' => 'Genel Üretim Giderleri Verimlilik Farkları', 'type' => 'expense'],
            ['code' => '734', 'name' => 'Genel Üretim Giderleri Kapasite Farkları', 'type' => 'expense'],
            ['code' => '740', 'name' => 'Hizmet Üretim Maliyeti', 'type' => 'expense'],
            ['code' => '741', 'name' => 'Hizmet Üretim Maliyeti Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '742', 'name' => 'Hizmet Üretim Maliyeti Fark Hesapları', 'type' => 'expense'],
            ['code' => '750', 'name' => 'Araştırma ve Geliştirme Giderleri', 'type' => 'expense'],
            ['code' => '751', 'name' => 'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '752', 'name' => 'Araştırma ve Geliştirme Gider Farkları', 'type' => 'expense'],
            ['code' => '760', 'name' => 'Pazarlama, Satış ve Dağıtım Giderleri', 'type' => 'expense'],
            ['code' => '761', 'name' => 'Pazarlama, Satış ve Dağıtım Giderleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '762', 'name' => 'Pazarlama, Satış ve Dağıtım Giderleri Fark Hesabı', 'type' => 'expense'],
            ['code' => '770', 'name' => 'Genel Yönetim Giderleri', 'type' => 'expense'],
            ['code' => '771', 'name' => 'Genel Yönetim Giderleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '772', 'name' => 'Genel Yönetim Gider Farkları Hesabı', 'type' => 'expense'],
            ['code' => '780', 'name' => 'Finansman Giderleri', 'type' => 'expense'],
            ['code' => '781', 'name' => 'Finansman Giderleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '782', 'name' => 'Finansman Giderleri Fark Hesabı', 'type' => 'expense'],
            // 7/B seçeneği maliyet hesapları
            ['code' => '790', 'name' => 'İlk Madde ve Malzeme Giderleri', 'type' => 'expense'],
            ['code' => '791', 'name' => 'İşçi Ücret ve Giderleri', 'type' => 'expense'],
            ['code' => '792', 'name' => 'Memur Ücret ve Giderleri', 'type' => 'expense'],
            ['code' => '793', 'name' => 'Dışarıdan Sağlanan Fayda ve Hizmetler', 'type' => 'expense'],
            ['code' => '794', 'name' => 'Çeşitli Giderler', 'type' => 'expense'],
            ['code' => '795', 'name' => 'Vergi, Resim ve Harçlar', 'type' => 'expense'],
            ['code' => '796', 'name' => 'Amortismanlar ve Tükenme Payları', 'type' => 'expense'],
            ['code' => '797', 'name' => 'Finansman Giderleri (7/B)', 'type' => 'expense'],
            ['code' => '798', 'name' => 'Gider Çeşitleri Yansıtma Hesabı', 'type' => 'expense'],
            ['code' => '799', 'name' => 'Üretim Maliyet Hesabı', 'type' => 'expense'],
        ];
    }
}
